---

#Configure a basic nginx server
- name: Configure webserver w/ nginx and TLS
  hosts: vagrant
  become: yes
  become_method: sudo
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost
  tasks:
    - name: install nginx
      yum: name=nginx update_cache=yes

    - name: create cert directories
      file: path=/etc/nginx/ssl state=directory

    - name: create sites-available
      file: path=/etc/nginx/sites-available state=directory

    - name: copy TLS key
      copy: src=files/nginx.key dest={{ key_file }} owner=root mode=0600
      notify: restart nginx

    - name: copy TLS cert
      copy: src=files/nginx.crt dest={{ cert_file }}
      notify: restart nginx

    - name: copy nginx conf file
      copy: src=files/nginx.conf dest=/etc/nginx/nginx.conf

    - name: copy server conf file
      template: src=templates/server.conf.j2 dest={{ conf_file }}
      notify: restart nginx
 
    - name: enable config
      file: >
        dest=/etc/nginx/conf.d/default
        src={{ conf_file }}
        state=link
      notify: restart nginx

    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644
      notify: restart nginx

    - name: stop firewall
      service: name=firewalld state=stopped enabled=no

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted enabled=yes
