#!/usr/bin/env ansible-playbook
---

- name: deploy mezzanine containers
  hosts: vagrant
  become: yes
  become_method: sudo
  gather_facts: True
  vars_files:
    - secrets.yml
  vars:
    database_name: mezzanine
    database_user: mezzanine
    database_port: 5432
    gunicorn_port: 8000
    docker_host: "{{ lookup('env', 'DOCKER_HOST') | regex_replace('^tcp://(.*):\\d+$','\\\\1') | default('localhost',true)}}"
    project_dir: /srv/project
    website_domain: "{{ docker_host }}"
    mezzanine_env:
      SECRET_KEY: "{{ secret_key }}"
      NEVERCACHE_KEY: "{{ nevercache_key }}"
      ALLOWED_HOSTS: "*"
      DATABASE_NAME: "{{ database_name }}"
      DATABASE_USER: "{{ database_user }}"
      DATABASE_PASSWORD: "{{ database_password }}"
      DATABASE_HOST: "{{ database_host }}"
      DATABASE_PORT: "{{ database_port }}"
      GUNICORN_PORT: "{{ gunicorn_port }}"
      PROJECT_DIR: "{{ project_dir }}"
      ADMIN_PASSWORD: "{{ admin_password }}"
      WEBSITE_DOMAIN: "{{ website_domain }}"

  tasks:
    - name: start postgres
      docker:
        image: jyore/mezzanine-docker:postgresql
        name: postgres
        publish_all_ports: True
        env:
          POSTGRES_USER: "{{ database_user }}"
          POSTGRES_PASSWORD: "{{ database_password }}"

    - name: capture db ip address and mapped port
      set_fact:
        database_host: "{{ docker_containers[0].NetworkSettings.IPAddress }}"
        mapped_database_port: "{{ docker_containers[0].NetworkSettings.Ports['5432/tcp'][0].HostPort }}"

    - name: wait for database
      wait_for: host={{ docker_host }} port={{ mapped_database_port }}
 
    - name: start the memcached container
      docker:
        image: jyore/mezzanine-docker:memcached
        name: memcached

    - name: start the mezzanine container
      docker:
        name: mezzanine
        image: jyore/mezzanine-docker:mezzanine
        env: "{{ mezzanine_env }}"
        links: memcached

    #TODO: Determine better wait condition than time, but this 'works'
    - name: wait for mezzanine availability
      wait_for: timeout=2

    - name: initialize database
      command: docker exec -t mezzanine ./manage.py {{ item }} --noinput
      with_items:
        - syncdb
        - migrate

    - name: set the site id
      command: docker exec -t mezzanine /srv/scripts/setsite.py

    - name: set the admin password
      command: docker exec -t mezzanine /srv/scripts/setadmin.py

    - name: start the cert container
      docker:
        image: jyore/mezzanine-docker:certs
        name: certs

    - name: run nginx
      docker:
        image: jyore/mezzanine-docker:nginx
        ports:
         - 8080:80
         - 8443:443
        name: nginx
        volumes_from:
          - mezzanine
          - certs
        links: mezzanine
