---

#Configure a basic nginx server
- name: Configure webserver w/ nginx
  hosts: vagrant
  become: yes
  become_method: sudo
  tasks:
    - name: install nginx
      yum: name=nginx update_cache=yes

    - name: create sites-available
      file: path=/etc/nginx/sites-available state=directory

    - name: copy nginx conf file
      copy: src=files/nginx.conf dest=/etc/nginx/nginx.conf

    - name: copy nginx server file
      copy: src=files/server.conf dest=/etc/nginx/sites-available/default

    - name: enable config
      file: >
        dest=/etc/nginx/conf.d/default
        src=/etc/nginx/sites-available/default
        state=link

    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644

    - name: stop firewall
      service: name=firewalld state=stopped enabled=no

    - name: restart nginx
      service: name=nginx state=restarted enabled=yes
